[2022-05-16 10:00:53,063] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Collect_Data_Dag.get_data_src_measures_taken_country_wise scheduled__2022-05-12T18:00:00+00:00 [queued]>
[2022-05-16 10:00:53,105] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Collect_Data_Dag.get_data_src_measures_taken_country_wise scheduled__2022-05-12T18:00:00+00:00 [queued]>
[2022-05-16 10:00:53,106] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-05-16 10:00:53,108] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-05-16 10:00:53,110] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-05-16 10:00:53,266] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): get_data_src_measures_taken_country_wise> on 2022-05-12 18:00:00+00:00
[2022-05-16 10:00:53,292] {standard_task_runner.py:52} INFO - Started process 209 to run task
[2022-05-16 10:00:53,328] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Collect_Data_Dag', 'get_data_src_measures_taken_country_wise', 'scheduled__2022-05-12T18:00:00+00:00', '--job-id', '146', '--raw', '--subdir', 'DAGS_FOLDER/collect_data_dag.py', '--cfg-path', '/tmp/tmp1omwl_02', '--error-file', '/tmp/tmp6xq76daz']
[2022-05-16 10:00:53,333] {standard_task_runner.py:80} INFO - Job 146: Subtask get_data_src_measures_taken_country_wise
[2022-05-16 10:00:53,648] {task_command.py:369} INFO - Running <TaskInstance: Collect_Data_Dag.get_data_src_measures_taken_country_wise scheduled__2022-05-12T18:00:00+00:00 [running]> on host 6c2369487cbf
[2022-05-16 10:00:55,060] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=Collect_Data_Dag
AIRFLOW_CTX_TASK_ID=get_data_src_measures_taken_country_wise
AIRFLOW_CTX_EXECUTION_DATE=2022-05-12T18:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-12T18:00:00+00:00
[2022-05-16 10:00:55,063] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-05-16 10:00:55,066] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python3 /opt/***/dags/scripts/dag_data_source_api_5.py']
[2022-05-16 10:00:55,122] {subprocess.py:85} INFO - Output:
[2022-05-16 10:01:01,218] {subprocess.py:96} INFO - Command exited with return code 0
[2022-05-16 10:01:01,287] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Collect_Data_Dag, task_id=get_data_src_measures_taken_country_wise, execution_date=20220512T180000, start_date=20220516T100053, end_date=20220516T100101
[2022-05-16 10:01:01,356] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-05-16 10:01:01,503] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
