[2022-05-16 10:01:02,201] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: stop_live_stream_Dag.stop_producer_twitter_data scheduled__2022-05-12T18:00:00+00:00 [queued]>
[2022-05-16 10:01:02,225] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: stop_live_stream_Dag.stop_producer_twitter_data scheduled__2022-05-12T18:00:00+00:00 [queued]>
[2022-05-16 10:01:02,226] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-05-16 10:01:02,228] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2022-05-16 10:01:02,229] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-05-16 10:01:02,252] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): stop_producer_twitter_data> on 2022-05-12 18:00:00+00:00
[2022-05-16 10:01:02,269] {standard_task_runner.py:52} INFO - Started process 428 to run task
[2022-05-16 10:01:02,271] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'stop_live_stream_Dag', 'stop_producer_twitter_data', 'scheduled__2022-05-12T18:00:00+00:00', '--job-id', '155', '--raw', '--subdir', 'DAGS_FOLDER/stop_live_stream_dags.py', '--cfg-path', '/tmp/tmpfcnoz7ce', '--error-file', '/tmp/tmpbc_jcqih']
[2022-05-16 10:01:02,280] {standard_task_runner.py:80} INFO - Job 155: Subtask stop_producer_twitter_data
[2022-05-16 10:01:02,444] {task_command.py:369} INFO - Running <TaskInstance: stop_live_stream_Dag.stop_producer_twitter_data scheduled__2022-05-12T18:00:00+00:00 [running]> on host 6c2369487cbf
[2022-05-16 10:01:03,661] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=stop_live_stream_Dag
AIRFLOW_CTX_TASK_ID=stop_producer_twitter_data
AIRFLOW_CTX_EXECUTION_DATE=2022-05-12T18:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-12T18:00:00+00:00
[2022-05-16 10:01:03,666] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-05-16 10:01:03,673] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'pkill -9 -f /opt/***/dags/scripts/producer_tweets.py']
[2022-05-16 10:01:03,951] {subprocess.py:85} INFO - Output:
[2022-05-16 10:01:04,246] {subprocess.py:96} INFO - Command exited with return code 1
[2022-05-16 10:01:04,675] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-05-16 10:01:04,803] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=stop_live_stream_Dag, task_id=stop_producer_twitter_data, execution_date=20220512T180000, start_date=20220516T100102, end_date=20220516T100104
[2022-05-16 10:01:05,041] {standard_task_runner.py:97} ERROR - Failed to execute job 155 for task stop_producer_twitter_data (Bash command failed. The command returned a non-zero exit code 1.; 428)
[2022-05-16 10:01:05,157] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-05-16 10:01:05,304] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
